Лабораторная работа №2
Programming-Classrooms/practicalworks-VadimStrashnov pull request #2
Opened 2023-12-10 17:09 UTC by VadimStrashnov

## Pull Request лабораторной работы №2

### Условие лабраторной работы

6. Написать программу, которая для заданного натурального числа  выполняет разложение числа на простые множители
9. Написать программу, которая для заданного натурального числа N находит, не превышающие это число дружественные
12. Написать программу, которая на заданном отрезке [a,b] натурального ряда чисел находит все числа Армстронга

### Вопросы по условию

Отсутствуют (P. s.  1 лаба отсутствует т.к.  винда с линуксом слетели((( )

2023-12-10 21:00 UTC, AnnaSatolina commented on laboratory-task-2/lab2.9.cpp
> +//Написать программу, которая для заданного натурального числа N находит, не превышающие это число дружественные
веселее было бы с обработкой исключений

2023-12-10 21:02 UTC, AnnaSatolina commented on laboratory-task-2/lab2.6.cpp
> +  for (int div = 2; div <= number; ++div)
название? не надо сокращать имя

2023-12-10 21:06 UTC, AlexandrOsiptsov commented on laboratory-task-2/lab2.12.cpp
> +}
Володька

2024-01-06 16:59 UTC, Voio77 requested changes
EXCEPTION!!!!!!!!!!

2024-06-17 16:22 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:42 UTC, merged