Лабораторная работа №3
Programming-Classrooms/practicalworks-VadimStrashnov pull request #3
Opened 2023-12-10 17:22 UTC by VadimStrashnov

## Pull Request лабораторной работы №3

### Условие лабраторной работы

Вариант 43
В одномерном массиве, состоящем из п вещественных элементов, вычислить:
- длину самой длинной цепочки попарно различных элементов, стоящих подряд;
- сумму целых частей элементов массива, расположенных после последнего отрицательного 
элемента.
Преобразовать массив таким образом, чтобы сначала располагались все элементы, 
отличающиеся от максимального не более чем на 20%, а потом — все остальные. Порядок 
следования элементов не изменять.
### Вопросы по условию

Отсутствуют

2023-12-10 19:51 UTC, AnnaSatolina requested changes
Плохо дело с клин кодом...И ещё момент с алгоритмом. Просьба исправить.

2023-12-10 19:51 UTC, AnnaSatolina commented on laboratory-task-3/lab3.cpp
> +void inputNumber(int& number)
почему int?

2023-12-10 19:51 UTC, AnnaSatolina commented on laboratory-task-3/lab3.cpp
> +      std::cout << " Wrong command " << '\n';
\n можно было дописать в конец строки, которую выводишь на консоль

2023-12-10 19:51 UTC, AnnaSatolina commented on laboratory-task-3/lab3.cpp
> +      return false;
так не делают. Уж тогда лучше возвращать 1, тип возвращаемого знатчения int,а не bool. А далее писать break вообще глупость. На return ты уже вывалился из функции.

2023-12-10 19:51 UTC, AnnaSatolina commented on laboratory-task-3/lab3.cpp
> +    completeArray(number, arr);
непонятные пустые строки...

2023-12-10 19:51 UTC, AnnaSatolina commented on laboratory-task-3/lab3.cpp
> +  for (int index = 0; index < number; ++index)
Весьма странно, где-то i, а где-то index

2023-12-10 19:51 UTC, AnnaSatolina commented on laboratory-task-3/lab3.cpp
> +  {
а если отрицательный элемент в конце? Как тогда? Где сообщение, что сумму посчитать нельзя?

2023-12-10 19:51 UTC, AnnaSatolina commented on laboratory-task-3/lab3.cpp
> +      if (arr[i] >= max(number, arr) * 0.8)
что за магическое число 0.8?

2023-12-10 19:51 UTC, AnnaSatolina commented on laboratory-task-3/lab3.cpp
> +        std::swap(lowBorder, highBorder);
switch лучше оформить функцией, типа меню

2023-12-10 19:51 UTC, AnnaSatolina commented on laboratory-task-3/lab3.cpp
> +        std::swap(lowBorder, highBorder);
лучше это сделать внутри функции checkBorders

2023-12-10 19:51 UTC, AnnaSatolina commented on laboratory-task-3/lab3.cpp
> +}
скобки не на своих местах

2023-12-12 19:02 UTC, VadimStrashnov commented on laboratory-task-3/lab3.cpp
> +      if (arr[i] >= max(number, arr) * 0.8)
в условии №3 числа не должны отличаться от максимального на 20%. Рассмотрены два случая: для положительного максимального числа (коэффициент 0.8) и для отрицательного (коэффициент 1.2). Это не магическое число)

2024-01-06 17:22 UTC, Voio77 requested changes
Читай комменты!

2024-01-06 17:22 UTC, Voio77 commented on laboratory-task-3/lab3.cpp
> +    for (int32_t i = 0; i < number; i++){
i++?

2024-01-06 17:22 UTC, Voio77 commented on laboratory-task-3/lab3.cpp
> +    return 0;
Юз, эяцм, ръчнмсн, ыфдф нчлюи щъьшмчищъ!
EXCEPTION!!!!!!!!!!!!!111

2024-06-17 16:22 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:43 UTC, merged