Лабораторная работа №4
Programming-Classrooms/practicalworks-VadimStrashnov pull request #4
Opened 2023-12-10 17:30 UTC by VadimStrashnov

## Pull Request лабораторной работы №4

### Условие лабраторной работы

Вариант 12
В целочисленной квадратной матрице nxn (3&lt;=n&lt;=101, n - нечетное) найти:
- найти сумму элементов нижнего правого треугольника;
- начиная с центра, обойти по спирали все элементы квадратной, выводя их в
порядке обхода. Обход выполнять по часовой стрелки, первый ход - вниз.

### Вопросы по условию

Отсутствуют

2023-12-10 20:46 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +
где return?

2023-12-10 20:46 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +    size_t** mtr = new size_t* { 0 };
добавить эту строку в функцию, где выделяется память под матрицу

2023-12-10 20:46 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +    size_t rows = 0, mode = 0, low_border = 0, high_border = 0;
лучше делать объявление каждой переменной в новой строке

2023-12-10 20:46 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +    std::cout << msg;
нет освобождения ресурсов, если вдруг что-то пойдёт не так

2023-12-10 20:46 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +      std::cout << " Input Min " << '\n';
А как же инглиш? Или тогда русский подключаем

2023-12-10 20:46 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +  std::cout << " Input  " << '\n';
что ввести? Недружелюбный интерфейс

2023-12-10 20:46 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +void inputBorder(size_t& border)
почему граница строго положительная? Для первой задачи этого не требуется

2023-12-10 20:46 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +    throw " Wrong size! ";
Лучше кажду строку с выводом заканчивать переходом на новую строку

2023-12-10 20:46 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +      }
будет кривой вывод у матрицы, если числа будут с разными знаками, например, или разным количеством цифр. Использовать манипуляторы вывода

2023-12-10 20:46 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +    }
почему f, k, g используются? ведь j локальная.

2023-12-10 20:46 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +}
здесь память не освобождается

2023-12-10 20:46 UTC, AnnaSatolina commented on laboratory-task-4/lab4.cpp
> +      }
я бы написала функцию проверки и добавила бы туда эти строки

2023-12-10 20:47 UTC, AnnaSatolina requested changes
Нужно еще поработать..

2024-01-06 17:37 UTC, Voio77 requested changes

2024-01-06 17:37 UTC, Voio77 commented on laboratory-task-4/lab4.cpp
> +        std::cout << msg;
и снова седая ночь

2024-06-17 16:22 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:42 UTC, merged