Лабораторная работа №1
Programming-Classrooms/practicalworks-VadimStrashnov pull request #5
Opened 2023-12-10 20:33 UTC by VadimStrashnov

## Pull Request лабораторной работы №1

### Условие лабраторной работы

Условие лабораторной работы №1 в файле. Пример №5

### Вопросы по условию

Отсутствуют

2023-12-10 21:13 UTC, AnnaSatolina requested changes
Код даже не компилируется

2023-12-10 21:13 UTC, AnnaSatolina commented on laboratory-task-1/lab1.cpp
> +
условие?

2023-12-10 21:13 UTC, AnnaSatolina commented on laboratory-task-1/lab1.cpp
> +  {
точность должна быть от 0 до 1

2023-12-10 21:13 UTC, AnnaSatolina commented on laboratory-task-1/lab1.cpp
> +  std::cout << " Write epsilon: " << '\n';
а эпсилон и точность - это не одно и то же?

2023-12-10 21:13 UTC, AnnaSatolina commented on laboratory-task-1/lab1.cpp
> +  if (epsilon <= 0  epsilon >= pow(10, accuracy))
а что это за  запись условия такая?

2023-12-10 21:13 UTC, AnnaSatolina commented on laboratory-task-1/lab1.cpp
> +  for (size_t i = 2; abs(term) > epsilon; ++i)
>=  должно быть

2023-12-10 21:13 UTC, AnnaSatolina commented on laboratory-task-1/lab1.cpp
> +  if (number <= -1  number > 1)
а что это за запись условия такая?

2024-01-06 16:50 UTC, Voio77 requested changes
Читай комменты!

2024-01-06 16:50 UTC, Voio77 commented on laboratory-task-1/lab1.cpp
> +}
EXCEPTION!!!!!!!!!!!!!!!!!!!!!!!!

2024-06-17 16:22 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:40 UTC, merged